### ISSUE TITLE
Xamarin Universal Library - One Place for all xamarin great resources

### ISSUE THREAD

**Issue by luismts** [wcoder/awesome-xamarin-bookmarks#1]
We are trying to bring you all together so the community has only one place for all xamarin great resources. So, we are reaching out to see how it can all be pulled together as there is some overlap.

Repository: https://github.com/xamarinuniverse/XamarinUniversalLibrary

**Comment by yauhenipakala** [comment]
Hi @luismts !

Glad to contribute expanding Xamarin community and join to Xamarin Universe Community!

Could you please add me to the Xamarin Universe organization on Github, for migrating resources from my account to the organization?

Linked: https://github.com/wcoder/open-source-xamarin-apps/issues/8

**Comment by yauhenipakala** [comment]
Hi @luismts, do you have any news?

**Comment by luismts** [comment]
Hey sorry for my late. I sent you the invitation
